const listings = [
    {
        id: 1,
        title: "10 Acre Farmland - Kansas",
        price: "$75,000",
        acres: 10,
        location: "Central, mukono",
        description: "Flat fertile farmland with existing water well. Perfect for crops or livestock.",
        image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["Water Well", "Good Soil", "Near Highway", "Fenced Partially"],
        zoning: "Agricultural",
        status: "Available",
        featured: true
    },
    {
        id: 2,
        title: "25 Acre Wooded Hunting Land",
        price: "$120,000",
        acres: 25,
        location: "kibwatule, kampala",
        description: "Heavily wooded with deer and turkey population. Small creek runs through property.",
        image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["Wooded", "Wildlife", "Creek", "Secluded"],
        zoning: "Recreational",
        status: "Available",
        featured: true
    },
    {
        id: 3,
        title: "5 Acre Residential Plot",
        price: "$45,000",
        acres: 5,
        location: "East, kyadondo",
        description: "Cleared lot with utilities available at road. Ready to build your dream home.",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["Utilities Available", "Cleared", "Good Drainage", "Quiet Area"],
        zoning: "Residential",
        status: "Available",
        featured: true
    },
    {
        id: 4,
        title: "50 Acre Ranch Land",
        price: "$350,000",
        acres: 50,
        location: "kaweepe, central Kampala",
        description: "Beautiful rolling hills with mountain views. Suitable for cattle or horses.",
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["Mountain Views", "Pasture", "Pond", "Barn Possible"],
        zoning: "Agricultural/Residential",
        status: "Available",
        featured: false
    },
    {
        id: 5,
        title: "2 Acre Lakefront Property",
        price: "$95,000",
        acres: 2,
        location: "kibwatule, kampala",
        description: "Direct lake access with 200 ft shoreline. Great for fishing and cabin building.",
        image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["Lake Front", "Fishing", "Private Access", "Trees"],
        zoning: "Recreational/Residential",
        status: "Available",
        featured: true
    },
    {
        id: 6,
        title: "15 Acre Vineyard Potential",
        price: "$225,000",
        acres: 15,
        location: "Ntinda, kampala",
        description: "South-facing slopes ideal for vineyard. Established irrigation system.",
        image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["Vineyard Ready", "Irrigation", "South Slope", "Winery Potential"],
        zoning: "Agricultural",
        status: "Available",
        featured: false
    },
    {
        id: 7,
        title: "8 Acres ",
        price: "$110,000",
        acres: 8,
        location: "Nabuti upper,Mukono",
        description: "Breath-taking mountain views. Partially cleared with year-round road access.",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["Mountain Views", "Road Access", "Partially Cleared", "Private"],
        zoning: "Residential",
        status: "Available",
        featured: false
    },
    {
        id: 8,
        title: "100 Acre Timber Investment",
        price: "$500,000",
        acres: 100,
        location: "Ntawo, mukono",
        description: "Mature timber with mixed hardwood and pine. Sustainable harvesting potential.",
        image: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["Timber", "Mixed Forest", "Investment", "Harvest Ready"],
        zoning: "Timber/Agricultural",
        status: "Available",
        featured: false
    },
    {
        id: 9,
        title: "3 Acre Riverfront Property",
        price: "$175,000",
        acres: 3,
        location: "seeta, mukono",
        description: "800 feet of river frontage. Excellent fishing and wildlife viewing.",
        image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        features: ["River Front", "Fishing", "Wildlife", "Secluded"],
        zoning: "Recreational",
        status: "Available",
        featured: false
    }
];